// Solana-flavored wallet name generator
// Format: {Adjective}{Noun}_{4-digit number}
// ~32M unique combinations (60 adj x 60 nouns x 9000 numbers)

const adjectives = [
  // Solana core concepts
  "RentExempt",
  "Staked",
  "Compressed",
  "Serialized",
  "Borsh",
  "Clockwork",
  "Turbine",
  "Parallelized",
  "Pipelined",
  "Slashed",
  "Delegated",
  "Finalized",
  "Deserialized",
  "Unstaked",
  "Frozen",
  "Executable",
  "Immutable",
  "Upgradeable",
  "CrossProgram",
  "Derived",

  // Solana culture / memes
  "Rugged",
  "Airdropped",
  "Bridged",
  "Liquidated",
  "Frontrun",
  "Sandwiched",
  "Sniped",
  "Minted",
  "Burned",
  "Swept",
  "Degenerate",
  "Diamond",
  "Paper",
  "Rekt",
  "Faded",
  "Bullish",
  "Bearish",
  "Crabbing",
  "Pumped",
  "Dumped",
  "Leveraged",
  "Overcollateralized",
  "Undercollateralized",
  "Yield",
  "Composable",
  "Permissionless",
  "Trustless",

  // Funny / absurd
  "Sleepy",
  "Chaotic",
  "Confused",
  "Unhinged",
  "Cozy",
  "Slightly",
  "Absolutely",
  "Suspiciously",
  "Dangerously",
  "Mildly",
  "Aggressively",
  "Reluctantly",
  "Accidentally",
  "Chronically",
  "Supremely",
  "Gloriously",
  "Tragically",
  "Hopelessly",
  "Violently",
  "Peacefully",
];

const nouns = [
  // Solana ecosystem references
  "Validator",
  "Lamport",
  "Anchor",
  "Phantom",
  "FireDancer",
  "Geyser",
  "Metaplex",
  "Helius",
  "Jito",
  "Marinade",
  "Orca",
  "Raydium",
  "Jupiter",
  "Drift",
  "Tensor",
  "Squads",
  "Realms",
  "Clockwork",
  "Switchboard",
  "Pyth",
  "Blink",
  "cNFT",
  "PDA",
  "CPI",
  "IDL",
  "Keypair",
  "Blockhash",
  "Epoch",
  "Slot",
  "Signer",

  // Animals (crypto culture)
  "Whale",
  "Dolphin",
  "Crab",
  "Ape",
  "Frog",
  "Shark",
  "Shrimp",
  "Bear",
  "Bull",
  "Degen",
  "Penguin",
  "Toucan",
  "Gecko",
  "Hamster",
  "Lobster",
  "Capybara",
  "Raccoon",
  "Possum",
  "Platypus",
  "Alpaca",

  // Funny characters / roles
  "Wizard",
  "Monk",
  "Samurai",
  "Pirate",
  "Goblin",
  "Peasant",
  "Overlord",
  "Intern",
  "Janitor",
  "Chad",
  "Sensei",
  "Shipper",
  "Lurker",
  "Grinder",
  "Maxi",
  "Enjoyer",
  "Survivor",
  "Tourist",
  "Refugee",
  "Nomad",
];

export function generateWalletName(): string {
  const adj = adjectives[Math.floor(Math.random() * adjectives.length)]!;
  const noun = nouns[Math.floor(Math.random() * nouns.length)]!;
  const num = Math.floor(Math.random() * 9000) + 1000; // 1000-9999
  return `${adj}${noun}_${num}`;
}

export { adjectives, nouns };
