import type { editor } from "monaco-editor";

/**
 * Monaco Editor themes aligned with Superteam Academy Design System v5.
 * These MUST use hex values — Monaco API does not support CSS custom properties.
 * Backgrounds use our warm neutral palette instead of cold grays.
 */

export const superteamDark: editor.IStandaloneThemeData = {
  base: "vs-dark",
  inherit: true,
  rules: [
    { token: "", foreground: "e2e8f0", background: "161b27" },
    { token: "comment", foreground: "64748b", fontStyle: "italic" },
    { token: "keyword", foreground: "b07aff" },
    { token: "keyword.control", foreground: "b07aff" },
    { token: "string", foreground: "14f195" },
    { token: "string.escape", foreground: "10c878" },
    { token: "number", foreground: "FBBF24" },
    { token: "type", foreground: "2DD4BF" },
    { token: "type.identifier", foreground: "2DD4BF" },
    { token: "class", foreground: "2DD4BF" },
    { token: "function", foreground: "dcdcaa" },
    { token: "function.declaration", foreground: "dcdcaa" },
    { token: "variable", foreground: "e2e8f0" },
    { token: "variable.predefined", foreground: "9945ff" },
    { token: "constant", foreground: "FBBF24" },
    { token: "operator", foreground: "94a3b8" },
    { token: "delimiter", foreground: "94a3b8" },
    { token: "delimiter.bracket", foreground: "94a3b8" },
    { token: "tag", foreground: "9945ff" },
    { token: "attribute.name", foreground: "2DD4BF" },
    { token: "attribute.value", foreground: "14f195" },
    { token: "regexp", foreground: "FBBF24" },
    { token: "annotation", foreground: "b07aff" },
    { token: "macro", foreground: "9945ff" },
  ],
  colors: {
    "editor.background": "#161b27",
    "editor.foreground": "#e2e8f0",
    "editor.lineHighlightBackground": "#1c2333",
    "editor.selectionBackground": "#2DD4BF44",
    "editor.inactiveSelectionBackground": "#2DD4BF1a",
    "editorCursor.foreground": "#14f195",
    "editorWhitespace.foreground": "#1e293b",
    "editorIndentGuide.background": "#1e293b",
    "editorIndentGuide.activeBackground": "#334155",
    "editorLineNumber.foreground": "#475569",
    "editorLineNumber.activeForeground": "#2DD4BF",
    "editor.selectionHighlightBackground": "#2DD4BF15",
    "editorBracketMatch.background": "#2DD4BF22",
    "editorBracketMatch.border": "#2DD4BF66",
    "editorGutter.background": "#161b27",
    "editorWidget.background": "#1c2333",
    "editorWidget.border": "#1e293b",
    "editorSuggestWidget.background": "#1c2333",
    "editorSuggestWidget.border": "#1e293b",
    "editorSuggestWidget.selectedBackground": "#2DD4BF33",
    "editorSuggestWidget.highlightForeground": "#14f195",
    "editorHoverWidget.background": "#1c2333",
    "editorHoverWidget.border": "#1e293b",
    "scrollbarSlider.background": "#2DD4BF22",
    "scrollbarSlider.hoverBackground": "#2DD4BF44",
    "scrollbarSlider.activeBackground": "#2DD4BF66",
    "minimap.background": "#161b27",
  },
};

export const superteamLight: editor.IStandaloneThemeData = {
  base: "vs",
  inherit: true,
  rules: [
    { token: "", foreground: "1C1917", background: "FFFFFF" },
    { token: "comment", foreground: "A8A29E", fontStyle: "italic" },
    { token: "keyword", foreground: "7c3aed" },
    { token: "keyword.control", foreground: "7c3aed" },
    { token: "string", foreground: "087068" },
    { token: "string.escape", foreground: "0B7E73" },
    { token: "number", foreground: "B45309" },
    { token: "type", foreground: "0D9488" },
    { token: "type.identifier", foreground: "0D9488" },
    { token: "class", foreground: "0D9488" },
    { token: "function", foreground: "6b5b00" },
    { token: "function.declaration", foreground: "6b5b00" },
    { token: "variable", foreground: "1C1917" },
    { token: "variable.predefined", foreground: "7c3aed" },
    { token: "constant", foreground: "B45309" },
    { token: "operator", foreground: "57534E" },
    { token: "delimiter", foreground: "57534E" },
    { token: "delimiter.bracket", foreground: "57534E" },
    { token: "tag", foreground: "7c3aed" },
    { token: "attribute.name", foreground: "0D9488" },
    { token: "attribute.value", foreground: "087068" },
    { token: "regexp", foreground: "B45309" },
    { token: "annotation", foreground: "7c3aed" },
    { token: "macro", foreground: "7c3aed" },
  ],
  colors: {
    "editor.background": "#FFFFFF",
    "editor.foreground": "#1C1917",
    "editor.lineHighlightBackground": "#F5F3EE",
    "editor.selectionBackground": "#0D948822",
    "editor.inactiveSelectionBackground": "#0D948811",
    "editorCursor.foreground": "#0D9488",
    "editorWhitespace.foreground": "#E7E4DD",
    "editorIndentGuide.background": "#E7E4DD",
    "editorIndentGuide.activeBackground": "#D4D0C7",
    "editorLineNumber.foreground": "#A8A29E",
    "editorLineNumber.activeForeground": "#0D9488",
    "editor.selectionHighlightBackground": "#0D948815",
    "editorBracketMatch.background": "#0D948815",
    "editorBracketMatch.border": "#0D948844",
    "editorGutter.background": "#FFFFFF",
    "editorWidget.background": "#FFFFFF",
    "editorWidget.border": "#E7E4DD",
    "editorSuggestWidget.background": "#FFFFFF",
    "editorSuggestWidget.border": "#E7E4DD",
    "editorSuggestWidget.selectedBackground": "#0D948815",
    "editorSuggestWidget.highlightForeground": "#087068",
    "editorHoverWidget.background": "#FFFFFF",
    "editorHoverWidget.border": "#E7E4DD",
    "scrollbarSlider.background": "#0D948815",
    "scrollbarSlider.hoverBackground": "#0D948833",
    "scrollbarSlider.activeBackground": "#0D948844",
    "minimap.background": "#FFFFFF",
  },
};

export const THEME_MAP = {
  dark: "superteam-dark",
  light: "superteam-light",
} as const;

export type ThemeName = (typeof THEME_MAP)[keyof typeof THEME_MAP];
